version: '3'

services:

  # postgres
  postgres:
    image: postgres:12.4
    container_name: 'postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
    volumes:
     - ./dumps:/db/dumps

  # redis
  redis:
    image: redis:5.0.9
    container_name: 'redis'
    restart: always
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: development
    command: redis-server --appendonly yes    
    volumes:
     - ./dumps:/db/dumps

  # mongo
  mongo:
    image: mongo:4.4.1
    container_name: 'mongo'
    restart: always
    ports:
      - '27017-27019:27017-27019'
    environment:
      MONGO_INITDB_DATABASE: development
      MONGO_INITDB_ROOT_USERNAME: development
      MONGO_INITDB_ROOT_PASSWORD: development
    volumes:
     - ./dumps:/db/dumps